# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: miayam.github.io
description: > # this means to ignore newlines until "baseurl:"
  Written words by Muhammad D. Ramadhan.
repository: https://github.com/miayam/miayam.github.io
url: https://miayam.github.io  # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: compressed

# Pagination settings
paginate: 10

permalink: /:categories/:year/:month/:day/:title

paginate_path: "/page/:num/"

# Theme settings
theme_mode: standard  # choices are: 'dark', 'standard', 'markdown'

# Customizations
your_name: Muhammad D. Ramadhan
email: muhammaddeni90@gmail.com
github: https://github.com/miayam

excerpt_separator: Read more.

navigation:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Archive
    url: /archive


category_pages:
  - text: JavaScript
    url: /js
    src: /images/javascript.png

# Plugins
gems:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-paginate
